// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLDmBEFAd6YmkYGYqkvOhjiiN9NCzIml0',
    appId: '1:509848346627:web:029c4cce22681a0b3f6e36',
    messagingSenderId: '509848346627',
    projectId: 'oner-7d34e',
    authDomain: 'oner-7d34e.firebaseapp.com',
    storageBucket: 'oner-7d34e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkcfzVjSYkD3s4gsPcBXMu53GOeYUCb_A',
    appId: '1:509848346627:android:9c9354772dd7fb4f3f6e36',
    messagingSenderId: '509848346627',
    projectId: 'oner-7d34e',
    storageBucket: 'oner-7d34e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA82XA7wpmCPCdj0nLv5zZTLOGmniMpaxE',
    appId: '1:509848346627:ios:2f53381b70ed1ba93f6e36',
    messagingSenderId: '509848346627',
    projectId: 'oner-7d34e',
    storageBucket: 'oner-7d34e.appspot.com',
    iosBundleId: 'com.example.oner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA82XA7wpmCPCdj0nLv5zZTLOGmniMpaxE',
    appId: '1:509848346627:ios:6b1b682a3640d44d3f6e36',
    messagingSenderId: '509848346627',
    projectId: 'oner-7d34e',
    storageBucket: 'oner-7d34e.appspot.com',
    iosBundleId: 'com.example.oner.RunnerTests',
  );
}
